name: Run tests

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Укажите нужную ветку
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Или '3.11', если тесты не работают на 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        pytest homework06/tests/test_bayes.py  homework06/tests/test_hackernews.py  # Путь к тестам, проверьте, что он правильный
