name: Run tests

# Укажите событие, которое будет запускать этот workflow
on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Запускать при создании pull request в ветку main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Checkout кода
    - name: Checkout code
      uses: actions/checkout@v2

    # Шаг 2: Установить версию Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Замените на нужную версию Python

    # Шаг 3: Установить зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Устанавливаем pytest для тестов
        # Установить другие зависимости, если есть requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Шаг 4: Запустить тесты
    - name: Run tests
      run: |
        pytest tests/lifegame_test.py  # Запуск теста
